// Generated by gencs from handyman/HandymanMsg.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace handyman 
	{
		[System.Serializable]
		public class HandymanMsg : RosMessage
		{
			public string message;
			public string detail;


			public HandymanMsg()
			{
				this.message = "";
				this.detail = "";
			}

			public HandymanMsg(string message, string detail)
			{
				this.message = message;
				this.detail = detail;
			}

			new public static string GetMessageType()
			{
				return "handyman/HandymanMsg";
			}

			new public static string GetMD5Hash()
			{
				return "83c3ad4b113aebdb7a85eba9ba595d50";
			}
		} // class HandymanMsg
	} // namespace handyman
} // namespace SIGVerse.ROSBridge

